spring.application.name=Task Management System
spring.datasource.url=jdbc:mysql://localhost:3306/myDB
spring.datasource.username=root
spring.datasource.password=AkoSiSam2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
